language: clojure
sudo: false
install:
  - wget -c https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O lein-stable
  - chmod 755 lein-stable
  - ./lein-stable
before_script:
  - ./lein-stable --version
after_success:
  - CLOVERAGE_VERSION=1.0.9 ./lein-stable with-profile dev,$VERSION cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
env:
  matrix:
    - VERSION='1.8'
    - VERSION='1.9'
    - VERSION='1.10'
script:
  - ./lein-stable with-profile dev,$VERSION test
  - ./lein-stable with-profile dev,$VERSION cljsbuild test
